leftnav:
- identifier: af9d2352-f049-4d9c-8ee1-a7c5b60de725
  name: Marguerite de Roberval Website
  pageRef: /external-resources/marguerite-de-roberval-website_af9d2352-f049-4d9c-8ee1-a7c5b60de725
  weight: 10
